name = "zephyr-hello-world"

#Router events table

[[tables]]
name = "events"

[[tables.columns]]
name = "e_type"
col_type = "BYTEA"

[[tables.columns]]
name = "token_a"
col_type = "BYTEA"

[[tables.columns]]
name = "token_b"
col_type = "BYTEA"

[[tables.columns]]
name = "amount_a"
col_type = "BYTEA"

[[tables.columns]]
name = "amount_b"
col_type = "BYTEA"

[[tables.columns]]
name = "account"
col_type = "BYTEA"

#Pairs table

[[tables]]
name = "pairs"

[[tables.columns]]
name = "address"
col_type = "BYTEA"

[[tables.columns]]
name = "token_a"
col_type = "BYTEA"

[[tables.columns]]
name = "token_b"
col_type = "BYTEA"

