name = "zephyr-soroswap"

#Soroswap Router events table

[[tables]]
name = "soroswap_router_events"

[[tables.columns]]
name = "e_type"
col_type = "BYTEA"

[[tables.columns]]
name = "token_a"
col_type = "BYTEA"

[[tables.columns]]
name = "token_b"
col_type = "BYTEA"

[[tables.columns]]
name = "amount_a"
col_type = "BYTEA"

[[tables.columns]]
name = "amount_b"
col_type = "BYTEA"

[[tables.columns]]
name = "account"
col_type = "BYTEA"

[[tables.columns]]
name = "timestamp"
col_type = "BYTEA"


#Soroswap Pairs table

[[tables]]
name = "soroswap_pairs"

[[tables.columns]]
name = "address"
col_type = "BYTEA"

[[tables.columns]]
name = "token_a"
col_type = "BYTEA"

[[tables.columns]]
name = "token_b"
col_type = "BYTEA"

[[tables.columns]]
name = "reserve_a"
col_type = "BYTEA"

[[tables.columns]]
name = "reserve_b"
col_type = "BYTEA"

#Soroswap Reserves changes table

[[tables]]
name = "soroswap_rsv_ch"

[[tables.columns]]
name = "address"
col_type = "BYTEA"

[[tables.columns]]
name = "reserve_a"
col_type = "BYTEA"

[[tables.columns]]
name = "reserve_b"
col_type = "BYTEA"

[[tables.columns]]
name = "timestamp"
col_type = "BYTEA"




