# swagger.yaml

openapi: 3.0.0
info:
  title: Zephyr Programs API
  version: 1.0.0
  description: API to obtain information from Soroswap, Phoenix, and Aqua
servers:
  - url: http://localhost:3000
tags:
  - name: Events
    description: API for events
  - name: Pairs
    description: API for pairs
  - name: Tokens
    description: API for tokens

components:
  schemas:
    MercuryEvent:
      type: object
      properties:
        tokenA:
          type: string
          description: Address of token A
        tokenB:
          type: string
          description: Address of token B
        eType:
          type: string
          enum: [swap, add, remove]
          description: Event type
        amountA:
          type: string
          description: Amount of token A
        amountB:
          type: string
          description: Amount of token B
        account:
          type: string
          description: Account address that performed the action
        timestamp:
          type: string
          description: Event timestamp
        txHash:
          type: string
          description: Transaction hash
        poolAddress:
          type: string
          description: Pool address associated with the event
      required:
        - tokenA
        - tokenB
        - eType
        - amountA
        - amountB
        - account
        - timestamp
        - txHash
        - poolAddress

    MercuryPair:
      type: object
      properties:
        tokenA:
          type: string
          description: Address of token A
        tokenB:
          type: string
          description: Address of token B
        address:
          type: string
          description: Pair address
        reserveA:
          type: string
          description: Reserve of token A
        reserveB:
          type: string
          description: Reserve of token B
      required:
        - tokenA
        - tokenB
        - address
        - reserveA
        - reserveB

    Token:
      type: object
      properties:
        name:
          type: string
          description: Token name
        code:
          type: string
          description: Token symbol
        issuer:
          type: string
          description: Token issuer address
        contract:
          type: string
          description: Token contract address
        org:
          type: string
          description: Organization associated with the token
        domain:
          type: string
          description: Domain associated with the token
        icon:
          type: string
          description: URL of the token icon
        decimals:
          type: integer
          description: Token decimals
      required:
        - name
        - code
        - issuer
        - contract
        - org
        - domain
        - icon
        - decimals

    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message
      required:
        - error

paths:
  /api/events:
    get:
      summary: Get a list of events for a specific protocol
      tags:
        - Events
      parameters:
        - in: query
          name: protocol
          schema:
            type: string
            enum: [soroswap, phoenix, aqua]
          required: true
          description: Protocol name (soroswap, phoenix, aqua)
        - in: query
          name: network
          schema:
            type: string
            enum: [MAINNET, TESTNET]
          required: true
          description: Network name (MAINNET, TESTNET)
        - in: query
          name: type
          schema:
            type: string
            enum: [swap, add, remove]
          description: Event type (swap, add, remove)
        - in: query
          name: address
          schema:
            type: string
          description: Specific pool address
      responses:
        '200':
          description: Successfully obtained event list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MercuryEvent'
        '400':
          description: Missing or invalid parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: No events found with the given parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/pairs:
    get:
      summary: Get a list of pairs for a specific protocol
      tags:
        - Pairs
      parameters:
        - in: query
          name: protocol
          schema:
            type: string
            enum: [soroswap, phoenix, aqua]
          required: true
          description: Protocol name (soroswap, phoenix, aqua)
        - in: query
          name: network
          schema:
            type: string
            enum: [MAINNET, TESTNET]
          required: true
          description: Network name (MAINNET, TESTNET)
        - in: query
          name: address
          schema:
            type: string
          description: Specific pair address
        - in: query
          name: full
          schema:
            type: string
            enum: ['true', 'false']
          description: Include all pairs without filtering
      responses:
        '200':
          description: Successfully obtained list of pairs
          content:
            application/json:
              schema:
                oneOf:
                  - type: array
                    items:
                      $ref: '#/components/schemas/MercuryPair'
                  - $ref: '#/components/schemas/MercuryPair'
        '400':
          description: Missing or invalid parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Pair not found for the provided address
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/tokens:
    get:
      summary: Get a list of tokens or a specific token for a protocol
      tags:
        - Tokens
      parameters:
        - in: query
          name: protocol
          schema:
            type: string
            enum: [soroswap, phoenix, aqua]
          required: true
          description: Protocol name (soroswap, phoenix, aqua)
        - in: query
          name: network
          schema:
            type: string
            enum: [MAINNET, TESTNET]
          required: true
          description: Network name (MAINNET, TESTNET)
        - in: query
          name: address
          schema:
            type: string
          description: Specific token address
      responses:
        '200':
          description: Successfully obtained list of tokens or a specific token
          content:
            application/json:
              schema:
                oneOf:
                  - type: array
                    items:
                      $ref: '#/components/schemas/Token'
                  - $ref: '#/components/schemas/Token'
        '400':
          description: Missing or invalid parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Token not found for the provided address
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
