name: Run tests

on: push
permissions:
  contents: write
  pull-requests: write 
  issues: read
  packages: none

jobs:
  test-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1


      - uses: docker/setup-buildx-action@v2
      - name: Build and run
        run: docker-compose up -d

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '20.10.0'

      - name: Open container
        run: bash scripts/run.sh
      
      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test